//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTickets.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieTickesDBEntities : DbContext
    {
        public MovieTickesDBEntities()
            : base("name=MovieTickesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Authentication> Authentications { get; set; }
        public DbSet<CinemaComment> CinemaComments { get; set; }
        public DbSet<CinemaRate> CinemaRates { get; set; }
        public DbSet<Cinema> Cinemas { get; set; }
        public DbSet<FilmComment> FilmComments { get; set; }
        public DbSet<FilmRate> FilmRates { get; set; }
        public DbSet<Film> Films { get; set; }
        public DbSet<Hall> Halls { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Seat> Seats { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<TicketReserve> TicketReserves { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersToRole> UsersToRoles { get; set; }
        public DbSet<ConfirmRegistrationKeys> ConfirmRegistrationKeys { get; set; }
    }
}
