//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTickets.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReserve
    {
        public int SeatId { get; set; }
        public int SessionId { get; set; }
        public int UserId { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
